### ISSUE TITLE
Feature request: Enable method to add draggable persistent effects to token

### ISSUE THREAD

**Issue by fraserstanton** [CarlosFdez/pf2e-persistent-damage#13]
It would be nice to have a method to drag persistent damage from the chat to a token.
Best usage I can think of is something like alchemist's fire where someone throws a bomb, and then you can drag the pre-defined persistent damage from the chat onto the appropriate token without needing to manually add the effect.
I know this is likely a multi-step process, but is there a way to set up a rules element that could be added to an item that could then be dragged to a token?
Just tossing out ideas.

**Comment by CarlosFdez** [comment]
You can kindof already do that, but the usability is kinda awful. If you add the effect via the form to an actor, and then drag it from the actor to the global items list, you can then drag it into the chat as an entity link and it'll work just fine.

I can probably make it so you can create a persistent damage effect as an unowned item via the forms, but I was thinking of leveraging rule elements by creating a custom rule. The problem though is that if I do that you won't be able to edit persistent damage very easily since the details page text fields would go away.

**Comment by fraserstanton** [comment]
How about just add instructions to your splash page for how to use the tool to create custom effects, that will fulfill what I want in the short term.
I have an alchemist in my party and I want to make my life easier for all the different persistent effects he can cause without having to type it in each time.

The other option would be to add each of the dice to the dialog for quick clicking.
e.g.
Dice: 1 (default) 2 3 5
Die: d4 d6 d8 d10 d12 d20
Type: rest of screen as it is ... so with 3 clicks you could set up the persistent effect. But this sounds like of effort for little gain.

**Comment by CarlosFdez** [comment]
New version will now convert any inline rolls of the form [[/r 2d6 #persistent fire]] or what have you into draggable effect links. Clicking on them shows error messages but you can safely ignore them, I'll figure out something for that later.

**Comment by fraserstanton** [comment]
I can't get it to work, no error messages or anything and nothing in the console. Tried dragging as GM, player, but nothing. World and modules all updated. Odd.

**Comment by CarlosFdez** [comment]
Can I see what you're trying to do via some screenshots? What is the inline roll you're doing?

Its a bit picky with the roll flavor message. Maybe too picky at this point. Would need to see what you're trying to do.
EDIT: Also update again, there was another bug.

**Comment by fraserstanton** [comment]
I updated it to the latest version but still not working for me.
I tried something simple. Major acid bomb vs a rat. Tried dragging the effect onto the rat but it did not work, nothing happened, no errors in the console. Tried in foundry, tried logging in from web as GM, nothing seems to work. Not sure other clues I can give you sorry. I guess I could try recording a gif.

![image](https://user-images.githubusercontent.com/85046656/122315760-8af81b80-cecf-11eb-989e-43e7ffe15793.png)

**Comment by fraserstanton** [comment]
https://user-images.githubusercontent.com/85046656/122316401-aadc0f00-ced0-11eb-83b8-2b93570f3e85.mp4

**Comment by CarlosFdez** [comment]
I'm trying to narrow down why its not working. I assume the problem is when its a roll note? What happens if its in like a creature description? Doing some tests to see if its a roll note thing just in case.

EDIT: Managed to reproduce it. Yeah its failing for roll notes. Gonna look into why.
EDIT2: Found out why....its a roll card issue. Easy fix, although annoying.
EDIT3: Fixed, will push in the next release and make a comment when I do.

**Comment by CarlosFdez** [comment]
Released a new version. Fingers crossed.

**Comment by fraserstanton** [comment]
Tested and it works! Thanks for all the fixes Carlos. (sorry for delay I got distracted)
