### ISSUE TITLE
Process Persistent Damage macro fails to remove condition icon from actor

### ISSUE THREAD

**Issue by apoapostolov** [CarlosFdez/pf2e-persistent-damage#2]
After a success roll, the condition is removed from the actor and future rounds of combat will not auto-trigger persistent damage macro, however the icon remains on the actor and is not removed.

**Comment by CarlosFdez** [comment]
That's interesting, because I'm testing it and the icon does indeed get removed. That icon could have gotten there another way though.

Do you have the effects panel activated? Is the icon there in the effects? What does it say?

Alternatively, it could be that you accidentally added the effect twice (double clicked apply), and it only got removed once. When that happens, it shows twice in the effect panel, but once on the actor. I should probably make a note of that if its the case, or do a lockout in some way if a persistent damage of the same type is on the actor.

**Comment by apoapostolov** [comment]
What happens is:
1. I give an actor, tested with both PC and NPC, a condition, i..e Bleeding 1
2. I roll Process until I get success.
3. The condition icon on the actor token blinks removed and then is re-added. It no longer appears in Effect Panel or the Character Sheet Effects tab. However, the icon with an empty label is applied to the token and can be manually removed from the condition list. 

![image](https://user-images.githubusercontent.com/4083812/111840496-24ca1f80-8905-11eb-9141-6de4e31f374f.png)

I use Monk's Little Details mod to see the labels of the conditions (helps a lot with PF2) and it shows me that this condition has no text applied to it. It seems just the icon itself is re-applied to the token. Once I remove that icon from the token, the custom condition can no longer be found on the condition list, as it is ad-hoc icon and not a condition. 

![image](https://user-images.githubusercontent.com/4083812/111840681-7c688b00-8905-11eb-876f-f6212c7786e0.png)

**Comment by CarlosFdez** [comment]
That is...extremely weird. What shows on the effects panel? This one:
![image](https://user-images.githubusercontent.com/1286721/111846253-c8530a00-88dc-11eb-8dca-f2052ebd8771.png)

**Comment by CarlosFdez** [comment]
If Monk's Little Details is disabled, does the bug go away? If so it might be an issue with that module and it might need some investigation. What happens if you for example remove bless? What happens if you manually remove the persistent damage from the effects panel instead of waiting for "success"?

EDIT: Even with monk's little details disabled, the icons are still going away. Likely not the cause. Very strange. Is PF2E on the most recent versions? Can you test with all modules off? Some modules on?

**Comment by apoapostolov** [comment]
I located the issue - conflict with https://gitlab.com/woodentavern/status-icon-counters
I am not sure why I am using this as I never got it to work for PF2 and dev/support has been dead for 5 months but it never had conflict and I kept it running. I turned it off and behavior is now normal. Sorry for raising the alarm.

**Comment by CarlosFdez** [comment]
Nah, its a big help. Now I can add it as an incompatibility lmao.
