### ISSUE TITLE
Add Good/Evil damage types

### ISSUE THREAD

**Issue by JamzTheMan** [CarlosFdez/pf2e-persistent-damage#4]
Could you add Good and Evil types? Champions, for instance, can do Cha good persistent damage around level 10.

Maybe add positive/negative as well for a full row?

Maybe an "untyped" one for a generic type that may show up. For instance a Flame Oracle can take 1d6 damage with major curse but it is not reduced by fire resistance so Fire wouldn't be appropriate to use (and so they may have this curse while also taking fire persistent damage which stacks AFAIK)

**Comment by CarlosFdez** [comment]
Was actually in the middle of that when you posted the issue, since someone on the discord actually asked for that last night. It was held back by other stuff I was also working on though. Try updating and give it a try.

Well, except untyped. I will need to ask core pf2e how they plan to do that for their resists/immunities thing, so I can tackle it a similar way.

**Comment by JamzTheMan** [comment]
Nice! Good work so far :)

**Comment by CarlosFdez** [comment]
Will close for now. for now might be best just to remember that flame oracles can't reduce fire resistance.
